datasets:
  ilsvrc2012:
    name: &dataset_name 'ilsvrc2012'
    type: 'ImageFolder'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      val:
        dataset_id: &imagenet_val !join [*dataset_name, '/val']
        params:
          root: !join [*root_dir, '/val']
          transform_params:
            - type: 'Resize'
              params:
                size: 448
            - type: 'CenterCrop'
              params:
                size: [416, 416]
            - type: 'ToTensor'
              params:

models:
  model:
    name: 'ladon'
    classification:
      name: 'splittable_resnet'
      params:
        num_classes: 1000
        pretrained: True
        bottleneck_config:
          name: 'FPBasedResNetBottleneck'
          params:
            num_bottleneck_channels: 24
            num_target_channels: 256
        resnet_name: 'resnet50'
        pre_transform_params:
        skips_avgpool: False
        skips_fc: False
        analysis_config:
          analyzes_after_compress: True
          analyzer_configs:
            - type: 'FileSizeAnalyzer'
              params:
                unit: 'KB'
        org_model_ckpt_file_path_or_url: 'https://download.pytorch.org/models/resnet50-11ad3fa6.pth'
      ckpt: './resource/ckpt/ilsvrc2012/ladon/ilsvrc2012-splittable_resnet50-fp-beta5.12_from_resnet50.pt'
    detection:
      name: 'faster_rcnn_model'
      params:
        pretrained: False
        progress: False
        num_classes: 91
        backbone_config:
          name: 'splittable_resnet'
          params:
            num_classes: 1000
            pretrained: False
            inplanes: 2048
            bottleneck_config:
              name: 'FPBasedResNetBottleneck'
              params:
                num_bottleneck_channels: 24
                num_target_channels: 256
            resnet_name: 'resnet50'
            pre_transform_params:
            skips_avgpool: False
            skips_fc: False
            analysis_config:
              analyzes_after_compress: True
              analyzer_configs:
                - type: 'FileSizeAnalyzer'
                  params:
                    unit: 'KB'
          ckpt: './resource/ckpt/ilsvrc2012/ladon/ilsvrc2012-splittable_resnet50-fp-beta5.12_from_resnet50.pt'
        backbone_fpn_kwargs:
          return_layer_dict:
            bottleneck_layer: '1'
            layer2: '2'
            layer3: '3'
            layer4: '4'
          in_channels_list: [256, 512, 1024, 2048]
          out_channels: 256
          analysis_config:
            analyzes_after_compress: True
            analyzer_configs:
              - type: 'FileSizeAnalyzer'
                params:
                  unit: 'KB'
          analyzable_layer_key: 'bottleneck_layer'
        in_channels_stage2: 256
        min_size: 416
        max_size: 416
        start_ckpt_file_path: './resource/ckpt/coco2017/ladon/coco2017-faster_rcnn_splittable_resnet50-fp-beta5.12_fpn.pt'
    segmentation:
      name: 'deeplabv3_model'
      params:
        pretrained: False
        pretrained_backbone_name:
        num_classes: 21
        uses_aux: True
        num_input_channels: 2048
        num_aux_channels: 1024
        return_layer_dict:
          layer3: 'aux'
          layer4: 'out'
        analysis_config:
          analyzes_after_compress: True
          analyzer_configs:
            - type: 'FileSizeAnalyzer'
              params:
                unit: 'KB'
        analyzable_layer_key: 'bottleneck_layer'
        backbone_config:
          name: 'splittable_resnet'
          params:
            num_classes: 1000
            pretrained: False
            bottleneck_config:
              name: 'FPBasedResNetBottleneck'
              params:
                num_bottleneck_channels: 24
                num_target_channels: 256
            resnet_name: 'resnet50'
            pre_transform_params:
            skips_avgpool: True
            skips_fc: True
          ckpt: './resource/ckpt/ilsvrc2012/ladon/ilsvrc2012-splittable_resnet50-fp-beta5.12_from_resnet50.pt'
        start_ckpt_file_path: './resource/ckpt/pascal_voc2012/ladon/pascal_voc2012-deeplabv3_splittable_resnet50-fp-beta5.12.pt'

test:
  test_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 1
    num_workers: 16
