datasets:
  pascal_voc:
    name: &dataset_name 'pascal_voc2012'
    type: 'VOCSegmentation'
    root: &root_dir '~/dataset'
    splits:
      val:
        dataset_id: &pascal_val !join [*dataset_name, '/val']
        params:
          root: *root_dir
          image_set: 'val'
          year: '2012'
          download: False
          transforms_compose_cls: 'CustomCompose'
          transforms_params:
            - type: 'CustomRandomResize'
              params:
                min_size: 416
                max_size: 416
                square: True
            - type: 'CustomToTensor'
              params:
                converts_sample: True
                converts_target: True

models:
  model:
    name: 'ladon'
    classification:
      name: 'splittable_resnest'
      params:
        num_classes: 1000
        pretrained: True
        inplanes: 2048
        bottleneck_config:
          name: 'FPBasedResNetBottleneck'
          params:
            num_bottleneck_channels: 32
            num_target_channels: 256
        resnest_name: 'resnest269e'
        pre_transform_params:
        skips_avgpool: False
        skips_fc: False
        analysis_config:
          analyzes_after_compress: True
          analyzer_configs:
            - type: 'FileSizeAnalyzer'
              params:
                unit: 'KB'
      ckpt: './resource/ckpt/ilsvrc2012/ladon/ilsvrc2012-splittable_resnest269e-fp-beta0.32_from_resnest269e.pt'
    detection:
      name: 'faster_rcnn_model'
      params:
        pretrained: False
        progress: False
        num_classes: 91
        backbone_config:
          name: 'splittable_resnest'
          params:
            num_classes: 1000
            pretrained: False
            inplanes: 2048
            bottleneck_config:
              name: 'FPBasedResNetBottleneck'
              params:
                num_bottleneck_channels: 32
                num_target_channels: 256
            resnest_name: 'resnest269e'
            pre_transform_params:
            skips_avgpool: False
            skips_fc: False
            analysis_config:
              analyzes_after_compress: True
              analyzer_configs:
                - type: 'FileSizeAnalyzer'
                  params:
                    unit: 'KB'
          ckpt: 'resource/ckpt/ilsvrc2012/ladon/ilsvrc2012-splittable_resnest269e-fp-beta0.32_from_resnest269e.pt'
        backbone_fpn_kwargs:
          return_layer_dict:
            bottleneck_layer: '1'
            layer2: '2'
            layer3: '3'
            layer4: '4'
          in_channels_list: [256, 512, 1024, 2048]
          out_channels: 256
          analysis_config:
            analyzes_after_compress: True
            analyzer_configs:
              - type: 'FileSizeAnalyzer'
                params:
                  unit: 'KB'
          analyzable_layer_key: 'bottleneck_layer'
        in_channels_stage2: 256
        min_size: 416
        max_size: 416
        start_ckpt_file_path: './resource/ckpt/coco2017/ladon/coco2017-faster_rcnn_splittable_resnest269e-fp-beta0.32_fpn.pt'
    segmentation:
      name: 'deeplabv3_model'
      params:
        pretrained: False
        pretrained_backbone_name:
        num_classes: 21
        uses_aux: True
        num_input_channels: 2048
        num_aux_channels: 1024
        return_layer_dict:
          layer3: 'aux'
          layer4: 'out'
        analysis_config:
          analyzes_after_compress: True
          analyzer_configs:
            - type: 'FileSizeAnalyzer'
              params:
                unit: 'KB'
        analyzable_layer_key: 'bottleneck_layer'
        backbone_config:
          name: 'splittable_resnest'
          params:
            num_classes: 1000
            pretrained: False
            inplanes: 2048
            bottleneck_config:
              name: 'FPBasedResNetBottleneck'
              params:
                num_bottleneck_channels: 32
                num_target_channels: 256
            resnest_name: 'resnest269e'
            pre_transform_params:
            skips_avgpool: True
            skips_fc: True
        start_ckpt_file_path: './resource/ckpt/pascal_voc2012/ladon/pascal_voc2012-deeplabv3_splittable_resnest269e-fp-beta0.32.pt'

test:
  test_data_loader:
    dataset_id: *pascal_val
    random_sample: False
    batch_size: 1
    num_workers: 16
    collate_fn: 'pascal_seg_eval_collate_fn'
