datasets:
  &pascal_val 'pascal_voc2012/val': !import_call
    _root: &root_dir '~/datasets'
    key: 'torchvision.datasets.VOCSegmentation'
    init:
      kwargs:
        root: *root_dir
        image_set: 'val'
        year: '2012'
        download: True
        transforms: !import_call
          key: 'custom.transform.CustomCompose'
          init:
            kwargs:
              transforms:
                - !import_call
                  key: 'custom.transform.CustomRandomResize'
                  init:
                    kwargs:
                      min_size: 416
                      max_size: 416
                      square: True
                - !import_call
                  key: 'sc2bench.transforms.misc.CustomToTensor'
                  init:
                    kwargs:
                      converts_sample: True
                      converts_target: True
                - !import_call
                  key: 'custom.transform.CustomNormalize'
                  init:
                    kwargs:
                      mean: [0.485, 0.456, 0.406]
                      std: [0.229, 0.224, 0.225]

models:
  model:
    key: 'ladon'
    classification:
      key: 'splittable_resnest'
      kwargs:
        num_classes: 1000
        pretrained: True
        inplanes: 2048
        bottleneck_config:
          key: 'FPBasedResNetBottleneck'
          kwargs:
            num_bottleneck_channels: 32
            num_target_channels: 256
        resnest_name: 'resnest269e'
        pre_transform:
        skips_avgpool: False
        skips_fc: False
        analysis_config:
          analyzes_after_compress: True
          analyzer_configs:
            - key: 'FileSizeAnalyzer'
              kwargs:
                unit: 'KB'
      src_ckpt: './resource/ckpt/ilsvrc2012/ladon/ilsvrc2012-splittable_resnest269e-fp-beta0.32_from_resnest269e.pt'
    detection:
      key: 'faster_rcnn_model'
      kwargs:
        pretrained: False
        progress: False
        num_classes: 91
        backbone_config:
          key: 'splittable_resnest'
          kwargs:
            num_classes: 1000
            pretrained: False
            inplanes: 2048
            bottleneck_config:
              key: 'FPBasedResNetBottleneck'
              kwargs:
                num_bottleneck_channels: 32
                num_target_channels: 256
            resnest_name: 'resnest269e'
            pre_transform:
            skips_avgpool: False
            skips_fc: False
            analysis_config:
              analyzes_after_compress: True
              analyzer_configs:
                - key: 'FileSizeAnalyzer'
                  kwargs:
                    unit: 'KB'
          src_ckpt: './resource/ckpt/ilsvrc2012/ladon/ilsvrc2012-splittable_resnest269e-fp-beta0.32_from_resnest269e.pt'
        backbone_fpn_kwargs:
          return_layer_dict:
            bottleneck_layer: '1'
            layer2: '2'
            layer3: '3'
            layer4: '4'
          in_channels_list: [256, 512, 1024, 2048]
          out_channels: 256
          analysis_config:
            analyzes_after_compress: True
            analyzer_configs:
              - key: 'FileSizeAnalyzer'
                kwargs:
                  unit: 'KB'
          analyzable_layer_key: 'bottleneck_layer'
        in_channels_stage2: 256
        min_size: 416
        max_size: 416
        start_ckpt_file_path: './resource/ckpt/coco2017/ladon/coco2017-faster_rcnn_splittable_resnest269e-fp-beta0.32_fpn.pt'
    segmentation:
      key: 'deeplabv3_model'
      kwargs:
        pretrained: False
        pretrained_backbone_name:
        num_classes: 21
        uses_aux: True
        num_input_channels: 2048
        num_aux_channels: 1024
        return_layer_dict:
          layer3: 'aux'
          layer4: 'out'
        analysis_config:
          analyzes_after_compress: True
          analyzer_configs:
            - key: 'FileSizeAnalyzer'
              kwargs:
                unit: 'KB'
        analyzable_layer_key: 'bottleneck_layer'
        backbone_config:
          key: 'splittable_resnest'
          kwargs:
            num_classes: 1000
            pretrained: False
            inplanes: 2048
            bottleneck_config:
              key: 'FPBasedResNetBottleneck'
              kwargs:
                num_bottleneck_channels: 32
                num_target_channels: 256
            resnest_name: 'resnest269e'
            pre_transform:
            skips_avgpool: True
            skips_fc: True
        start_ckpt_file_path: './resource/ckpt/pascal_voc2012/ladon/pascal_voc2012-deeplabv3_splittable_resnest269e-fp-beta0.32.pt'

test:
  test_data_loader:
    dataset_id: *pascal_val
    sampler:
      class_or_func: !import_get
        key: 'torch.utils.data.SequentialSampler'
      kwargs:
    collate_fn: 'pascal_seg_eval_collate_fn'
    kwargs:
      batch_size: 1
      num_workers: 16
