dependencies:
  - name: 'custom'

datasets:
  &coco_val coco2017/val: !import_call
    _name: &dataset_name 'coco2017'
    _root: &root_dir !join ['~/datasets/', *dataset_name]
    key: 'coco.dataset.coco_dataset'
    init:
      kwargs:
        img_dir_path: !join [*root_dir, '/val2017']
        ann_file_path: !join [*root_dir, '/annotations/instances_val2017.json']
        annotated_only: False
        is_segment: False

models:
  model:
    key: 'fasterrcnn_mobilenet_v3_large_320_fpn'
    kwargs:
      pretrained: True
      num_classes: 91

test:
  test_data_loader:
    dataset_id: *coco_val
    sampler:
      class_or_func: !import_get
        key: 'torch.utils.data.SequentialSampler'
      kwargs:
    collate_fn: 'coco_collate_fn'
    kwargs:
      batch_size: 1
      num_workers: 8
