dependencies:
  - name: 'custom'

datasets:
  &coco_train coco2017/train: &coco_train_dataset !import_call
    _name: &dataset_name 'coco2017'
    _root: &root_dir !join ['~/datasets/', *dataset_name]
    key: 'coco.dataset.coco_dataset'
    init:
      kwargs:
        img_dir_path: !join [*root_dir, '/train2017']
        ann_file_path: !join [*root_dir, '/annotations/instances_train2017.json']
        annotated_only: True
        random_horizontal_flip: 0.5
        is_segment: False
  &coco_val coco2017/val: !import_call
    key: 'coco.dataset.coco_dataset'
    init:
      kwargs:
        img_dir_path: !join [*root_dir, '/val2017']
        ann_file_path: !join [*root_dir, '/annotations/instances_val2017.json']
        annotated_only: False
        is_segment: False

models:
  model:
    key: 'faster_rcnn_model'
    kwargs:
      pretrained: False
      progress: False
      num_classes: 91
      backbone_config:
        key: 'splittable_resnest'
        kwargs:
          num_classes: 1000
          pretrained: False
          inplanes: 2048
          bottleneck_config:
            key: 'FPBasedResNetBottleneck'
            kwargs:
              num_bottleneck_channels: 32
              num_target_channels: 256
          resnest_name: 'resnest269e'
          pre_transform:
          skips_avgpool: False
          skips_fc: False
          analysis_config:
            analyzes_after_compress: True
            analyzer_configs:
              - key: 'FileSizeAnalyzer'
                kwargs:
                  unit: 'KB'
        src_ckpt: './resource/ckpt/ilsvrc2012/ladon/ilsvrc2012-splittable_resnest269e-fp-beta5.12_from_resnest269e.pt'
      backbone_fpn_kwargs:
        return_layer_dict:
          bottleneck_layer: '1'
          layer2: '2'
          layer3: '3'
          layer4: '4'
        in_channels_list: [256, 512, 1024, 2048]
        out_channels: 256
        analysis_config:
          analyzes_after_compress: True
          analyzer_configs:
            - key: 'FileSizeAnalyzer'
              kwargs:
                unit: 'KB'
        analyzable_layer_key: 'bottleneck_layer'
      in_channels_stage2: 256
      min_size: 416
      max_size: 416
      start_ckpt_file_path:
    experiment: &student_experiment !join [*dataset_name, '-faster_rcnn_splittable_resnest269e-fp-beta5.12_fpn']
    dst_ckpt: !join ['./resource/ckpt/coco2017/ladon/', *student_experiment, '.pt']

train:
  log_freq: 1000
  epoch_to_update: 0
  num_epochs: 26
  train_data_loader:
    dataset_id: *coco_train
    sampler:
      class_or_func: !import_get
        key: 'torch.utils.data.RandomSampler'
      kwargs:
    batch_sampler:
      key: 'GroupedBatchSampler'
      kwargs:
        batch_size: 8
        group_ids: !import_call
          key: 'custom.sampler.create_aspect_ratio_groups'
          init:
            kwargs:
              dataset: *coco_train_dataset
              aspect_ratio_group_factor: 3
    collate_fn: 'coco_collate_fn'
    kwargs:
      num_workers: 8
    cache_output:
  val_data_loader:
    dataset_id: *coco_val
    sampler:
      class_or_func: !import_get
        key: 'torch.utils.data.SequentialSampler'
      kwargs:
    collate_fn: 'coco_collate_fn'
    kwargs:
      batch_size: 1
      num_workers: 4
  model:
    forward_proc: 'forward_batch_target'
    adaptations:
    sequential: []
    frozen_modules: ['backbone.body']
    forward_hook:
      input: []
      output: []
    wrapper: 'DistributedDataParallel'
    requires_grad: True
  optimizer:
    key: 'SGD'
    kwargs:
      lr: 0.02
      momentum: 0.9
      weight_decay: 0.0001
    max_grad_norm: 1.0
  scheduler:
    key: 'MultiStepLR'
    kwargs:
      milestones: [16, 22]
      gamma: 0.1
  criterion:
    key: 'WeightedSumLoss'
    func2extract_model_loss: 'extract_model_loss_dict'
    kwargs:
      model_term:
        weight: 1.0

test:
  test_data_loader:
    dataset_id: *coco_val
    sampler:
      class_or_func: !import_get
        key: 'torch.utils.data.SequentialSampler'
      kwargs:
    collate_fn: 'coco_collate_fn'
    kwargs:
      batch_size: 1
      num_workers: 8
